// project.cc — write and read the generated project TOML.
//
// Copyright (C) 2026 nava. AGPLv3 or later; see LICENSE.

#include "project.hh"

#include <cstdint>
#include <fstream>
#include <stdexcept>
#include <string>

#include <toml++/toml.hpp>

namespace pb {
namespace {

std::string q(const std::string& value) {
    std::string out = "\"";
    for (char ch : value) {
        if (ch == '\\')
            out += "\\\\";
        else if (ch == '"')
            out += "\\\"";
        else if (ch == '\n')
            out += "\\n";
        else if (ch == '\t')
            out += "\\t";
        else if (ch == '\r')
            out += "\\r";
        else
            out += ch;
    }
    out += '"';
    return out;
}

std::string toc_inline(const std::vector<TocEntry>& toc) {
    if (toc.empty())
        return "[]";
    std::string rows;
    for (size_t i = 0; i < toc.size(); ++i) {
        if (i)
            rows += ", ";
        rows += '[';
        rows += q(toc[i].title);
        rows += ", ";
        rows += std::to_string(toc[i].page);
        rows += ", ";
        rows += std::to_string(toc[i].depth);
        rows += ']';
    }
    return "[" + rows + "]";
}

}  // namespace

void write_project(const std::string& out_path,
                   const std::string& book_path,
                   const std::string& title,
                   const std::string& author,
                   const std::vector<Chapter>& chapters,
                   const std::string& paper,
                   const std::string& notes) {
    std::string text;
    text += "# Generated by `print-books init`. Hand-editable.\n";
    text += "book = " + q(book_path) + "\n";
    text += "title = " + q(title) + "\n";
    text += "author = " + q(author) + "\n";
    text += "paper = " + q(paper) + "\n";
    text += "notes = " + q(notes) + "\n";
    text += "\n";
    for (const Chapter& ch : chapters) {
        text += "[[chapters]]\n";
        text += "number = " + std::to_string(ch.number) + "\n";
        text += "title = " + q(ch.title) + "\n";
        text += "first = " + std::to_string(ch.first_page) + "\n";
        text += "last = " + std::to_string(ch.last_page) + "\n";
        text += "toc = " + toc_inline(ch.toc) + "\n";
        text += "\n";
    }

    std::ofstream out(out_path, std::ios::binary | std::ios::trunc);
    if (!out)
        throw std::runtime_error("cannot write project TOML: " + out_path);
    out << text;
    if (!out)
        throw std::runtime_error("cannot write project TOML: " + out_path);
}

std::vector<Chapter> read_chapters(const std::string& path) {
    const toml::table data = toml::parse_file(path);
    std::vector<Chapter> chapters;
    const toml::array* entries = data["chapters"].as_array();
    if (entries == nullptr)
        return chapters;

    for (const toml::node& node : *entries) {
        const toml::table* entry = node.as_table();
        if (entry == nullptr)
            continue;
        Chapter ch;
        ch.number = static_cast<int>((*entry)["number"].value_or(int64_t{0}));
        ch.title = (*entry)["title"].value_or(std::string{});
        ch.first_page = static_cast<int>((*entry)["first"].value_or(int64_t{0}));
        ch.last_page = static_cast<int>((*entry)["last"].value_or(int64_t{0}));
        if (const toml::array* toc = (*entry)["toc"].as_array()) {
            for (const toml::node& row_node : *toc) {
                const toml::array* row = row_node.as_array();
                if (row == nullptr || row->size() < 3)
                    continue;
                TocEntry e;
                e.title = (*row)[0].value_or(std::string{});
                e.page = static_cast<int>((*row)[1].value_or(int64_t{0}));
                e.depth = static_cast<int>((*row)[2].value_or(int64_t{0}));
                ch.toc.push_back(std::move(e));
            }
        }
        chapters.push_back(std::move(ch));
    }
    return chapters;
}

}  // namespace pb
