"""print-books: turn a PDF book into a printable interleaved notebook.

Why this exists: reading a book and taking notes means either writing in the
margins of a bought copy or keeping notes that lose their anchor to the page.
This takes a PDF and emits a notebook where every source page lands on a
left-hand sheet with a facing page for notes, and each chapter opens with a
LaTeX-style portrait.

Usage:
    print-books init BOOK.pdf [-o project.toml]
    print-books build project.toml [-o out.pdf] [--chapters all]

`init` probes the book (page count, outline, metadata) and writes a project
TOML you can hand-edit. `build` reads that TOML, plans the sides and emits the
PDF. Fully offline; the only dependencies are pikepdf and fontTools, both in
backend/.
"""

from __future__ import annotations

import argparse
import pathlib
import sys
import tomllib

from backend.glyphs_fonttools import OpenTypeGlyphs
from backend.pdf_pikepdf import chapters_from_outline, emit, probe
from core.geometry import paper
from core.plan import Chapter, NotesMode, TocEntry, plan_sides
from core.render import BookInfo, GridSpec, Layout, Renderer, Style
from core import units

NOTES_CHOICES = ("dots", "lines", "blank", "none")


def _q(value: str) -> str:
    """A TOML basic string, double-quoted and escaped."""
    out = ['"']
    for ch in value:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ch == "\r":
            out.append("\\r")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def _toc_inline(toc: tuple[TocEntry, ...]) -> str:
    rows = ", ".join(f"[{_q(e.title)}, {e.page}, {e.depth}]" for e in toc)
    return f"[{rows}]" if rows else "[]"


def _write_project(
    out: pathlib.Path,
    book_path: pathlib.Path,
    *,
    title: str,
    author: str,
    chapters: tuple[Chapter, ...],
    paper: str,
    notes: str,
) -> None:
    lines = [
        "# Generated by `print-books init`. Hand-editable.",
        f"book = {_q(str(book_path))}",
        f"title = {_q(title)}",
        f"author = {_q(author)}",
        f"paper = {_q(paper)}",
        f"notes = {_q(notes)}",
        "",
    ]
    for ch in chapters:
        lines.append("[[chapters]]")
        lines.append(f"number = {ch.number}")
        lines.append(f"title = {_q(ch.title)}")
        lines.append(f"first = {ch.first_page}")
        lines.append(f"last = {ch.last_page}")
        lines.append(f"toc = {_toc_inline(ch.toc)}")
        lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def _read_chapters(data: dict) -> tuple[Chapter, ...]:
    chapters: list[Chapter] = []
    for entry in data.get("chapters", []):
        toc = tuple(
            TocEntry(title=row[0], page=int(row[1]), depth=int(row[2]))
            for row in entry.get("toc", [])
        )
        chapters.append(
            Chapter(
                number=int(entry["number"]),
                title=str(entry["title"]),
                first_page=int(entry["first"]),
                last_page=int(entry["last"]),
                toc=toc,
            )
        )
    return tuple(chapters)


def cmd_init(args: argparse.Namespace) -> int:
    book = probe(args.book)
    chapters = chapters_from_outline(book)

    # A book with no outline is a supported case; without one, treat the whole
    # book as a single chapter so build still emits something useful.
    if not chapters:
        chapters = (
            Chapter(
                number=1,
                title=book.title or "Untitled",
                first_page=1,
                last_page=book.page_count,
                toc=(),
            ),
        )

    out = args.output or args.book.with_suffix(".toml")
    _write_project(
        out,
        args.book,
        title=book.title,
        author=book.author,
        chapters=chapters,
        paper=args.paper,
        notes=args.notes,
    )
    print(f"  {len(chapters)} chapters from the PDF outline")
    print(f"  {book.page_count} pages, {len(book.outline)} outline entries")
    print(f"  wrote {out}")
    return 0


def _notes_mode(name: str) -> NotesMode:
    return NotesMode(name)


def _select_chapters(
    chapters: tuple[Chapter, ...], spec: str
) -> tuple[Chapter, ...]:
    """`spec` is "all" or a comma list of chapter numbers and ranges (1,3-5)."""
    if spec == "all":
        return chapters
    wanted: set[int] = set()
    for part in spec.split(","):
        part = part.strip()
        if not part:
            continue
        if "-" in part:
            lo, hi = part.split("-", 1)
            wanted.update(range(int(lo), int(hi) + 1))
        else:
            wanted.add(int(part))
    return tuple(ch for ch in chapters if ch.number in wanted)


def cmd_build(args: argparse.Namespace) -> int:
    with args.project.open("rb") as fh:
        data = tomllib.load(fh)

    book_path = pathlib.Path(data["book"])
    chapters = _read_chapters(data)
    if not chapters:
        print(f"error: {args.project} declares no chapters", file=sys.stderr)
        return 2

    chapters = _select_chapters(chapters, args.chapters)
    if not chapters:
        print("error: --chapters selected nothing", file=sys.stderr)
        return 2

    notes = _notes_mode(data.get("notes", "dots"))
    paper_name = data.get("paper", "a4")
    title = data.get("title", "")
    author = data.get("author", "")

    book = probe(book_path)
    sides = plan_sides(chapters, notes=notes)

    roman = OpenTypeGlyphs.regular()
    italic = OpenTypeGlyphs.italic()
    renderer = Renderer(
        layout=Layout(
            paper=paper(paper_name),
            margin=units.mm(15.0),
            gutter=units.mm(10.0),
        ),
        grid=GridSpec(),
        style=Style(),
        book=BookInfo(title=title, author=author),
        roman=roman,
        italic=italic,
        notes=notes,
    )

    out = args.output or args.project.with_suffix(".pdf")
    emit(book, chapters, sides, renderer, out)

    sheets = (len(sides) + 1) // 2
    print(f"  {len(chapters)} chapters, {len(sides)} sides -> {sheets} sheets")
    print(f"  wrote {out}")
    return 0


def _parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="print-books",
        description="Turn a PDF book into a printable interleaved notebook.",
    )
    sub = p.add_subparsers(dest="command", required=True)

    init = sub.add_parser("init", help="probe a book and write a project TOML")
    init.add_argument("book", type=pathlib.Path, help="the source PDF")
    init.add_argument("-o", "--output", type=pathlib.Path, help="project TOML path")
    init.add_argument("--paper", default="a4", choices=["a4", "letter"])
    init.add_argument("--notes", default="dots", choices=NOTES_CHOICES)

    build = sub.add_parser("build", help="emit the notebook PDF")
    build.add_argument("project", type=pathlib.Path, help="a project TOML")
    build.add_argument("-o", "--output", type=pathlib.Path, help="output PDF path")
    build.add_argument("--chapters", default="all", help="all | 1 | 1,3-5")

    return p


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.command == "init":
        return cmd_init(args)
    if args.command == "build":
        return cmd_build(args)
    _parser().print_help()
    return 2


if __name__ == "__main__":
    sys.exit(main())
